name: CD - Publish and Deploy

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build-and-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app (prod)
        run: npm run build -- --configuration production

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u xlillium --password-stdin

      - name: Build and tag Docker image
        run: |
          docker build -t ghcr.io/xlillium/test-gh-deploy-frontend:${{ github.sha }} .
          docker tag ghcr.io/xlillium/test-gh-deploy-frontend:${{ github.sha }} ghcr.io/xlillium/test-gh-deploy-frontend:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/xlillium/test-gh-deploy-frontend:${{ github.sha }}
          docker push ghcr.io/xlillium/test-gh-deploy-frontend:latest
